# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: AWS KMS symmetric key for backend encryption - Multi-Region Primary Key (e.g. S3, etcd, OpenTofu)

Parameters:
  BackendEncryptionKmsKeyAlias:
    Type: String
    Description: Alias name for the backend encryption KMS key (without alias/ prefix)
    AllowedPattern: '^[a-zA-Z0-9/_-]+$'
    ConstraintDescription: Must be a valid KMS alias name (alphanumeric, hyphens, underscores, forward slashes)
  OrganizationId:
    Type: String
    Description: AWS Organizations ID for cross-account access control
    AllowedPattern: '^o-[a-z0-9]{10,32}$'
    ConstraintDescription: Must be a valid AWS Organizations ID (e.g., o-exampleorgid)

Resources:
  # Key rotation not enabled on purpose, mainly cost reasons.
  KMSKeyBackendEncryption:
    Type: AWS::KMS::Key
    Properties:
      BypassPolicyLockoutSafetyCheck: False
      Description: AWS KMS symmetric key for backend encryption - Multi-Region Primary Key (e.g. S3, etcd, OpenTofu)
      Enabled: True
      EnableKeyRotation: False
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'
          - Sid: DeleteProtection
            Principal: "*"
            Effect: Deny
            Action:
              - kms:ScheduleKeyDeletion
            Resource: "*"
          - Sid: AllowOrganizationAccess
            Effect: Allow
            Principal: "*"
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrganizationId
              ArnLike:
                aws:PrincipalArn:
                  - !Sub "arn:${AWS::Partition}:iam::*:role/OpenTofuRemoteBackendAccessRole"
                  - !Sub "arn:${AWS::Partition}:iam::*:role/GitHubOIDC-*-OpenTofuBackendAccess"
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: True
      Origin: AWS_KMS
      PendingWindowInDays: 30
      Tags:
        - Key: Environment
          Value: Production
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  KMSKeyBackendEncryptionAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${BackendEncryptionKmsKeyAlias}
      TargetKeyId: !Ref KMSKeyBackendEncryption

Outputs:
  KMSKeyBackendEncryptionName:
    Value: !Ref KMSKeyBackendEncryption
    Export:
      Name: !Sub ${AWS::StackName}-KMSKeyBackendEncryptionName
  KMSKeyBackendEncryptionArn:
    Value: !GetAtt KMSKeyBackendEncryption.Arn
    Export:
      Name: !Sub ${AWS::StackName}-KMSKeyBackendEncryptionArn
