# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

# KMSKeyForBackendEncryptionPrimary

AWSTemplateFormatVersion: 2010-09-09
Description: AWS KMS symmetric key for backend encryption - Multi-Region Primary Key (e.g. S3, etcd, OpenTofu)

Parameters:
  BackendEncryptionKmsKeyAlias:
    Type: String
    Description: Alias name for the backend encryption KMS key (without alias/ prefix)
    Default: backend-encryption

Resources:
  KMSKeyBackendEncryption:
    Type: AWS::KMS::Key
    Properties:
      BypassPolicyLockoutSafetyCheck: False
      Description: AWS KMS symmetric key for backend encryption - Multi-Region Primary Key (e.g. S3, etcd, OpenTofu)
      Enabled: True
      EnableKeyRotation: False
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'
          - Sid: DeleteProtection
            Principal: "*"
            Effect: Deny
            Action:
              - kms:ScheduleKeyDeletion
            Resource: "*"
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: True
      Origin: AWS_KMS
      PendingWindowInDays: 30
      Tags:
        - Key: Environment
          Value: Production
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  KMSKeyBackendEncryptionAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${BackendEncryptionKmsKeyAlias}
      TargetKeyId: !Ref KMSKeyBackendEncryption

Outputs:
  KMSKeyBackendEncryptionName:
    Value: !Ref KMSKeyBackendEncryption
    Export:
      Name: !Sub ${AWS::StackName}-KMSKeyBackendEncryptionName
  KMSKeyBackendEncryptionArn:
    Value: !GetAtt KMSKeyBackendEncryption.Arn
    Export:
      Name: !Sub ${AWS::StackName}-KMSKeyBackendEncryptionArn
